name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    env:
      NUGET_FEED_URL: https://pkgs.dev.azure.com/HiteshGhori/Phoenix/_packaging/ReportMigratorModels/nuget/v3/index.json
      NUGET_FEED_USERNAME: 'Azure DevOps'
      PACKAGE_PROJECT: './AzureArtifact.Models.csproj'
      DOTNET_VERSION: '8.0.x'
      PACKAGE_VERSION: 1.0.${{ github.run_number }}
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Authenticate with Azure Artifacts
        run: |
          dotnet nuget add source "$NUGET_FEED_URL" \
            --name AzureArtifacts \
            --username "$NUGET_FEED_USERNAME" \
            --password "9RNORobzyUjQPy9OgokdX7oZIaH3zE5VL3GoukiWC39ErOT2DPWoJQQJ99BFACAAAAA9nnGqAAASAZDO3exR" \
            --store-password-in-clear-text

      - name: Restore dependencies
        run: dotnet restore "$PACKAGE_PROJECT" --source AzureArtifacts

      - name: Build project
        run: dotnet build "$PACKAGE_PROJECT" --no-restore --configuration Release

      - name: Pack NuGet package
        run: dotnet pack "$PACKAGE_PROJECT" --no-build --configuration Release --output ./nupkgs /p:PackageVersion=${{ env.PACKAGE_VERSION }}

      - name: Push NuGet package to Azure Artifacts
        run: |
          dotnet nuget push "./nupkgs/*.nupkg" \
            --source AzureArtifacts \
            --api-key AzureDevOps
